server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cow?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    username: root            # 너 환경에 맞게
    password: yourpass        # 너 환경에 맞게
  jpa:
    hibernate:
      ddl-auto: validate      # 개발초기엔 update도 OK
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: true
    locations: classpath:db/migrationa