spring:
  application:
    name: COW-MATCHING-BE
  datasource:
    url: jdbc:mysql://localhost:3307/cow?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    username: appuser
    password: apppass
  jpa:
    hibernate:
      ddl-auto: update   # 개발 중엔 update 추천, 운영 땐 validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect   # 여기 변경
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 8080