spring:
  application:
    name: COW-MATCHING-BE
  datasource:
    url: jdbc:mysql://localhost:13306/cow_app?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    username: frizsbeen
    password: Www001009!
    driver-class-name: com.mysql.cj.jdbc.Driver   # driver 명시
    hikari:
      maximum-pool-size: 8
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: update   # 운영 전환 시 validate 권장
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

logging:
  level:
    org.springframework.web: DEBUG